### ISSUE TITLE
unable to run the basic setup.

### ISSUE THREAD

**Issue by DinoJay** [mekwall/koa-webpack-dev-server#1]
Hey mekwall,

first of all thank you for making dev server for koa. But I'm unable to run it.

I get the following error:

---

koa-webpack-dev-server/src/index.js:54
    this.app.use(function\* (next) {
                         ^
SyntaxError: Unexpected token *
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/djan/dev/hello-webpack/node_modules/koa-webpack-dev-server/index.js:1:80)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)

---

**Comment by mekwall** [comment]
You're most likely missing the `--harmony-generators` flag when running node/gulp. Please see https://github.com/koajs/koa/issues/179 for more info.
